// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg1D_uRh605GJjtIE4pJqDxAZS_r0tvDQ',
    appId: '1:943835626152:web:9da698203e624a72eea09d',
    messagingSenderId: '943835626152',
    projectId: 'mvvmsocial',
    authDomain: 'mvvmsocial.firebaseapp.com',
    storageBucket: 'mvvmsocial.firebasestorage.app',
    measurementId: 'G-JK0JDRXNFS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6FEeOkXFAZ1rWSVQxG4-V7ZNEVb2Ka8w',
    appId: '1:943835626152:android:89a6f13b2f7fc01aeea09d',
    messagingSenderId: '943835626152',
    projectId: 'mvvmsocial',
    storageBucket: 'mvvmsocial.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4Par5l5CZsVReHYFZXx8gX5cKTF9E7As',
    appId: '1:943835626152:ios:7e4fd6f6e871f54feea09d',
    messagingSenderId: '943835626152',
    projectId: 'mvvmsocial',
    storageBucket: 'mvvmsocial.firebasestorage.app',
    iosBundleId: 'com.example.mvvm',
  );
}
